// ─────────────────────────────────────────────────────────────────────────────
// EMOTION META
// Used by onboarding2, onboarding5, and any page that renders emotion cards
// ─────────────────────────────────────────────────────────────────────────────
const EMOTION_META = {
  happiness:      { label: 'Happiness',      sub: 'Warmth',             cssClass: 'f-happiness'      },
  anger:          { label: 'Anger',          sub: 'Social Tension',     cssClass: 'f-anger'          },
  fear:           { label: 'Fear',           sub: 'Withdrawal',         cssClass: 'f-fear'           },
  disgust:        { label: 'Disgust',        sub: 'Avoidance',          cssClass: 'f-disgust'        },
  sadness:        { label: 'Sadness',        sub: 'Withdrawal',         cssClass: 'f-sadness'        },
  envy:           { label: 'Envy',           sub: 'Social Tension',     cssClass: 'f-envy'           },
  contempt:       { label: 'Contempt',       sub: 'Distancing',         cssClass: 'f-contempt'       },
  pride:          { label: 'Pride',          sub: 'Self-assertion',     cssClass: 'f-pride'          },
  nostalgia:      { label: 'Nostalgia',      sub: 'Reflection',         cssClass: 'f-nostalgia'      },
  comfort:        { label: 'Comfort',        sub: 'Ease',               cssClass: 'f-comfort'        },
  gratitude:      { label: 'Gratitude',      sub: 'Appreciation',       cssClass: 'f-gratitude'      },
  love:           { label: 'Love',           sub: 'Connection',         cssClass: 'f-love'           },
  hope:           { label: 'Hope',           sub: 'Anticipation',       cssClass: 'f-hope'           },
  supported:      { label: 'Supported',      sub: 'Security',           cssClass: 'f-supported'      },
  safe:           { label: 'Safe',           sub: 'Calm',               cssClass: 'f-safe'           },
  jealousy:       { label: 'Jealousy',       sub: 'Insecurity',         cssClass: 'f-jealousy'       },
  resentment:     { label: 'Resentment',     sub: 'Bitterness',         cssClass: 'f-resentment'     },
  shame:          { label: 'Shame',          sub: 'Self-consciousness', cssClass: 'f-shame'          },
  guilt:          { label: 'Guilt',          sub: 'Remorse',            cssClass: 'f-guilt'          },
  rejection:      { label: 'Rejection',      sub: 'Exclusion',          cssClass: 'f-rejection'      },
  betrayal:       { label: 'Betrayal',       sub: 'Broken Trust',       cssClass: 'f-betrayal'       },
  loneliness:     { label: 'Loneliness',     sub: 'Isolation',          cssClass: 'f-loneliness'     },
  disappointment: { label: 'Disappointment', sub: 'Unmet Expectations', cssClass: 'f-disappointment' },
  numbness:       { label: 'Numbness',       sub: 'Disconnection',      cssClass: 'f-numbness'       },
  insecurity:     { label: 'Insecurity',     sub: 'Self-doubt',         cssClass: 'f-insecurity'     },
  boredom:        { label: 'Boredom',        sub: 'Restlessness',       cssClass: 'f-boredom'        },
  overwhelmed:    { label: 'Overwhelmed',    sub: 'Overload',           cssClass: 'f-overwhelmed'    },
  triumph:        { label: 'Triumph',        sub: 'Achievement',        cssClass: 'f-triumph'        },
  craving:        { label: 'Craving',        sub: 'Desire',             cssClass: 'f-craving'        },
  excitement:     { label: 'Excitement',     sub: 'Enthusiasm',         cssClass: 'f-excitement'     },
  determination:  { label: 'Determination',  sub: 'Drive',              cssClass: 'f-determination'  },
  confidence:     { label: 'Confidence',     sub: 'Self-assurance',     cssClass: 'f-confidence'     },
  inspired:       { label: 'Inspired',       sub: 'Creativity',         cssClass: 'f-inspired'       },
  compassion:     { label: 'Compassion',     sub: 'Caring',             cssClass: 'f-compassion'     },
  admiration:     { label: 'Admiration',     sub: 'Respect',            cssClass: 'f-admiration'     },
  sympathy:       { label: 'Sympathy',       sub: 'Understanding',      cssClass: 'f-sympathy'       },
  empathy:        { label: 'Empathy',        sub: 'Shared Feeling',     cssClass: 'f-empathy'        },
  romance:        { label: 'Romance',        sub: 'Intimacy',           cssClass: 'f-romance'        },
};

// ─────────────────────────────────────────────────────────────────────────────
// BLEND MAP  — 780 unique emotion pair combinations
// Key format: 'emotion_a+emotion_b'  (always alphabetical order)
// Lookup:  getBlend('happiness', 'anger')  →  'Passionate Fury'
// ─────────────────────────────────────────────────────────────────────────────
const BLEND_MAP_FULL = { 

  // happiness +
  'anger+happiness':          'Passionate Fury',
  'fear+happiness':           'Thrilled Nervousness',
  'disgust+happiness':        'Guilty Pleasure',
  'happiness+sadness':        'Bittersweet',
  'envy+happiness':           'Wistful Joy',
  'contempt+happiness':       'Smug Satisfaction',
  'happiness+pride':          'Triumphant Joy',
  'happiness+nostalgia':      'Warm Remembrance',
  'comfort+happiness':        'Contentment',
  'gratitude+happiness':      'Radiant Thankfulness',
  'happiness+love':           'Euphoria',
  'happiness+hope':           'Optimism',
  'happiness+supported':      'Cherished',
  'happiness+safe':           'Peaceful Joy',
  'envy+happiness':           'Wistful Joy',
  'happiness+jealousy':       'Conflicted Elation',
  'happiness+resentment':     'Hollow Celebration',
  'happiness+shame':          'Bashful Pride',
  'guilt+happiness':          'Conflicted Pleasure',
  'happiness+rejection':      'Brave Resilience',
  'betrayal+happiness':       'Cautious Delight',
  'happiness+loneliness':     'Isolated Joy',
  'disappointment+happiness': 'Tempered Hope',
  'happiness+numbness':       'Faded Bliss',
  'happiness+insecurity':     'Fragile Happiness',
  'boredom+happiness':        'Restless Content',
  'happiness+overwhelmed':    'Joyful Chaos',
  'happiness+triumph':        'Elation',
  'craving+happiness':        'Eager Delight',
  'excitement+happiness':     'Exhilaration',
  'determination+happiness':  'Driven Joy',
  'confidence+happiness':     'Radiant Assurance',
  'happiness+inspired':       'Creative Bliss',
  'compassion+happiness':     'Warm Generosity',
  'admiration+happiness':     'Inspired Awe',
  'happiness+sympathy':       'Gentle Joy',
  'empathy+happiness':        'Connected Delight',
  'happiness+romance':        'Tender Bliss',

  // anger +
  'anger+fear':               'Defensive Panic',
  'anger+disgust':            'Outrage',
  'anger+sadness':            'Anguish',
  'anger+envy':               'Bitter Rage',
  'anger+contempt':           'Disdainful Fury',
  'anger+pride':              'Righteous Indignation',
  'anger+nostalgia':          'Rueful Anger',
  'anger+comfort':            'Simmering Tension',
  'anger+gratitude':          'Conflicted Relief',
  'anger+love':               'Passionate Conflict',
  'anger+hope':               'Frustrated Optimism',
  'anger+supported':          'Defended',
  'anger+safe':               'Guarded',
  'anger+jealousy':           'Possessive Rage',
  'anger+resentment':         'Seething Bitterness',
  'anger+shame':              'Humiliated Fury',
  'anger+guilt':              'Remorseful Anger',
  'anger+rejection':          'Wounded Pride',
  'anger+betrayal':           'Scorned',
  'anger+loneliness':         'Isolated Rage',
  'anger+disappointment':     'Bitter Let-down',
  'anger+numbness':           'Cold Fury',
  'anger+insecurity':         'Defensive Anxiety',
  'anger+boredom':            'Restless Aggression',
  'anger+overwhelmed':        'Explosive Stress',
  'anger+triumph':            'Vindicated',
  'anger+craving':            'Desperate Hunger',
  'anger+excitement':         'Frenzied Energy',
  'anger+determination':      'Fierce Drive',
  'anger+confidence':         'Aggressive Assurance',
  'anger+inspired':           'Rebellious Creativity',
  'anger+compassion':         'Protective Wrath',
  'anger+admiration':         'Envious Respect',
  'anger+sympathy':           'Empathetic Frustration',
  'anger+empathy':            'Righteous Sorrow',
  'anger+romance':            'Stormy Passion',

  // fear +
  'disgust+fear':             'Horrified Revulsion',
  'fear+sadness':             'Dread',
  'envy+fear':                'Anxious Longing',
  'contempt+fear':            'Nervous Disdain',
  'fear+pride':               'Vulnerable Ego',
  'fear+nostalgia':           'Haunted Memories',
  'comfort+fear':             'Uneasy Calm',
  'fear+gratitude':           'Relieved Anxiety',
  'fear+love':                'Vulnerable Attachment',
  'fear+hope':                'Anxious Optimism',
  'fear+supported':           'Nervous Security',
  'fear+safe':                'Cautious Peace',
  'fear+jealousy':            'Paranoid Longing',
  'fear+resentment':          'Bitter Anxiety',
  'fear+shame':               'Mortified Fear',
  'fear+guilt':               'Dreaded Remorse',
  'fear+rejection':           'Terror of Exclusion',
  'betrayal+fear':            'Shattered Trust',
  'fear+loneliness':          'Isolated Terror',
  'disappointment+fear':      'Hopeless Dread',
  'fear+numbness':            'Frozen Shock',
  'fear+insecurity':          'Paralysing Self-doubt',
  'boredom+fear':             'Dreaded Stagnation',
  'fear+overwhelmed':         'Panic',
  'fear+triumph':             'Relieved Victory',
  'craving+fear':             'Fearful Desire',
  'excitement+fear':          'Nervous Anticipation',
  'determination+fear':       'Courageous Resolve',
  'confidence+fear':          'Brave Uncertainty',
  'fear+inspired':            'Fearful Curiosity',
  'compassion+fear':          'Protective Worry',
  'admiration+fear':          'Intimidated Awe',
  'fear+sympathy':            'Worried Kindness',
  'empathy+fear':             'Fearful Understanding',
  'fear+romance':             'Vulnerable Desire',

  // disgust +
  'disgust+sadness':          'Mournful Repulsion',
  'disgust+envy':             'Contemptuous Longing',
  'contempt+disgust':         'Utter Disdain',
  'disgust+pride':            'Offended Dignity',
  'disgust+nostalgia':        'Tainted Memories',
  'comfort+disgust':          'Uneasy Relief',
  'disgust+gratitude':        'Reluctant Appreciation',
  'disgust+love':             'Complicated Devotion',
  'disgust+hope':             'Reluctant Optimism',
  'disgust+supported':        'Uneasy Acceptance',
  'disgust+safe':             'Uncomfortable Security',
  'disgust+jealousy':         'Envious Repulsion',
  'disgust+resentment':       'Deep Bitterness',
  'disgust+shame':            'Self-Revulsion',
  'disgust+guilt':            'Nauseating Remorse',
  'disgust+rejection':        'Repulsed Exclusion',
  'betrayal+disgust':         'Revolted Betrayal',
  'disgust+loneliness':       'Repulsed Isolation',
  'disappointment+disgust':   'Disillusioned Revulsion',
  'disgust+numbness':         'Numb Repulsion',
  'disgust+insecurity':       'Self-loathing',
  'boredom+disgust':          'Apathetic Revulsion',
  'disgust+overwhelmed':      'Overwhelmed Repulsion',
  'disgust+triumph':          'Tainted Victory',
  'craving+disgust':          'Shameful Desire',
  'disgust+excitement':       'Morbid Fascination',
  'determination+disgust':    'Resolute Rejection',
  'confidence+disgust':       'Assured Disapproval',
  'disgust+inspired':         'Subversive Creativity',
  'compassion+disgust':       'Troubled Care',
  'admiration+disgust':       'Conflicted Respect',
  'disgust+sympathy':         'Reluctant Empathy',
  'disgust+empathy':          'Troubled Understanding',
  'disgust+romance':          'Complicated Attraction',

  // sadness +
  'envy+sadness':             'Sorrowful Longing',
  'contempt+sadness':         'Melancholic Disdain',
  'pride+sadness':            'Dignified Grief',
  'nostalgia+sadness':        'Wistful Sorrow',
  'comfort+sadness':          'Tender Grief',
  'gratitude+sadness':        'Tearful Appreciation',
  'love+sadness':             'Heartache',
  'hope+sadness':             'Melancholic Hope',
  'sadness+supported':        'Comforted Grief',
  'sadness+safe':             'Gentle Sorrow',
  'jealousy+sadness':         'Longing Sorrow',
  'resentment+sadness':       'Embittered Grief',
  'sadness+shame':            'Sorrowful Regret',
  'guilt+sadness':            'Remorseful Grief',
  'rejection+sadness':        'Heartbroken',
  'betrayal+sadness':         'Devastated',
  'loneliness+sadness':       'Deep Solitude',
  'disappointment+sadness':   'Dejection',
  'numbness+sadness':         'Hollow Grief',
  'insecurity+sadness':       'Fragile Sorrow',
  'boredom+sadness':          'Listless Melancholy',
  'overwhelmed+sadness':      'Exhausted Grief',
  'sadness+triumph':          'Hard-Won Victory',
  'craving+sadness':          'Yearning Sorrow',
  'excitement+sadness':       'Bittersweet Anticipation',
  'determination+sadness':    'Grieving Resolve',
  'confidence+sadness':       'Resilient Sorrow',
  'inspired+sadness':         'Melancholic Creativity',
  'compassion+sadness':       'Deep Empathy',
  'admiration+sadness':       'Reverent Grief',
  'sadness+sympathy':         'Sorrowful Kindness',
  'empathy+sadness':          'Shared Sorrow',
  'romance+sadness':          'Longing',

  // envy +
  'contempt+envy':            'Bitter Superiority',
  'envy+pride':               'Competitive Drive',
  'envy+nostalgia':           'Nostalgic Longing',
  'comfort+envy':             'Restless Comfort',
  'envy+gratitude':           'Grateful Longing',
  'envy+love':                'Jealous Devotion',
  'envy+hope':                'Ambitious Yearning',
  'envy+supported':           'Resentful Security',
  'envy+safe':                'Uneasy Stability',
  'envy+jealousy':            'Consuming Envy',
  'envy+resentment':          'Toxic Bitterness',
  'envy+shame':               'Ashamed Longing',
  'envy+guilt':               'Guilty Desire',
  'envy+rejection':           'Bitter Exclusion',
  'betrayal+envy':            'Betrayed Longing',
  'envy+loneliness':          'Isolated Longing',
  'disappointment+envy':      'Bitter Disappointment',
  'envy+numbness':            'Hollow Desire',
  'envy+insecurity':          'Fearful Longing',
  'boredom+envy':             'Restless Desire',
  'envy+overwhelmed':         'Overwhelmed Longing',
  'envy+triumph':             'Reluctant Admiration',
  'craving+envy':             'Obsessive Desire',
  'envy+excitement':          'Excited Longing',
  'determination+envy':       'Driven Ambition',
  'confidence+envy':          'Competitive Confidence',
  'envy+inspired':            'Inspired Ambition',
  'compassion+envy':          'Empathetic Longing',
  'admiration+envy':          'Aspiring Awe',
  'envy+sympathy':            'Empathetic Desire',
  'empathy+envy':             'Understood Longing',
  'envy+romance':             'Jealous Passion',

  // contempt +
  'contempt+pride':           'Arrogance',
  'contempt+nostalgia':       'Cynical Nostalgia',
  'comfort+contempt':         'Smug Ease',
  'contempt+gratitude':       'Reluctant Thanks',
  'contempt+love':            'Complicated Devotion',
  'contempt+hope':            'Cynical Optimism',
  'contempt+supported':       'Patronised',
  'contempt+safe':            'Hollow Security',
  'contempt+jealousy':        'Disdainful Envy',
  'contempt+resentment':      'Deep Scorn',
  'contempt+shame':           'Humiliated Disdain',
  'contempt+guilt':           'Guilty Contempt',
  'contempt+rejection':       'Scornful Exclusion',
  'betrayal+contempt':        'Scorned Betrayal',
  'contempt+loneliness':      'Isolated Disdain',
  'contempt+disappointment':  'Disillusioned Contempt',
  'contempt+numbness':        'Apathetic Disdain',
  'contempt+insecurity':      'Defensive Contempt',
  'boredom+contempt':         'Jaded Contempt',
  'contempt+overwhelmed':     'Overwhelmed Disdain',
  'contempt+triumph':         'Vindictive Victory',
  'contempt+craving':         'Disdainful Desire',
  'contempt+excitement':      'Jaded Curiosity',
  'contempt+determination':   'Ruthless Drive',
  'contempt+confidence':      'Arrogant Assurance',
  'contempt+inspired':        'Rebellious Genius',
  'compassion+contempt':      'Troubled Compassion',
  'admiration+contempt':      'Ambivalent Respect',
  'contempt+sympathy':        'Patronising Kindness',
  'contempt+empathy':         'Reluctant Understanding',
  'contempt+romance':         'Complicated Attraction',

  // pride +
  'nostalgia+pride':          'Proud Legacy',
  'comfort+pride':            'Dignified Ease',
  'gratitude+pride':          'Humble Pride',
  'love+pride':               'Devoted Pride',
  'hope+pride':               'Ambitious Confidence',
  'pride+supported':          'Empowered',
  'pride+safe':               'Secure Pride',
  'jealousy+pride':           'Competitive Insecurity',
  'pride+resentment':         'Offended Dignity',
  'pride+shame':              'Wounded Pride',
  'guilt+pride':              'Conflicted Achievement',
  'pride+rejection':          'Dignified Resilience',
  'betrayal+pride':           'Betrayed Dignity',
  'loneliness+pride':         'Solitary Dignity',
  'disappointment+pride':     'Deflated Pride',
  'numbness+pride':           'Hollow Achievement',
  'insecurity+pride':         'Fragile Confidence',
  'boredom+pride':            'Restless Achievement',
  'overwhelmed+pride':        'Burdened Achievement',
  'pride+triumph':            'Glorious Victory',
  'craving+pride':            'Ambitious Drive',
  'excitement+pride':         'Exhilarated Confidence',
  'determination+pride':      'Resolute Ambition',
  'confidence+pride':         'Unshakeable Self-belief',
  'inspired+pride':           'Creative Confidence',
  'compassion+pride':         'Noble Generosity',
  'admiration+pride':         'Inspired Achievement',
  'pride+sympathy':           'Generous Understanding',
  'empathy+pride':            'Compassionate Strength',
  'pride+romance':            'Devoted Passion',

  // nostalgia +
  'comfort+nostalgia':        'Warm Reminiscence',
  'gratitude+nostalgia':      'Thankful Remembrance',
  'love+nostalgia':           'Sentimental Devotion',
  'hope+nostalgia':           'Hopeful Remembrance',
  'nostalgia+supported':      'Remembered Connection',
  'nostalgia+safe':           'Comforting Memory',
  'jealousy+nostalgia':       'Envious Memory',
  'nostalgia+resentment':     'Bitter Memory',
  'nostalgia+shame':          'Regretful Memory',
  'guilt+nostalgia':          'Remorseful Reminiscence',
  'nostalgia+rejection':      'Painful Memory',
  'betrayal+nostalgia':       'Broken Memory',
  'loneliness+nostalgia':     'Lonely Reminiscence',
  'disappointment+nostalgia': 'Faded Expectation',
  'nostalgia+numbness':       'Distant Memory',
  'insecurity+nostalgia':     'Uncertain Past',
  'boredom+nostalgia':        'Restless Memory',
  'nostalgia+overwhelmed':    'Overwhelmed by Memory',
  'nostalgia+triumph':        'Nostalgic Achievement',
  'craving+nostalgia':        'Yearning for the Past',
  'excitement+nostalgia':     'Excited Reminiscence',
  'determination+nostalgia':  'Driven by Memory',
  'confidence+nostalgia':     'Assured Legacy',
  'inspired+nostalgia':       'Inspired by Memory',
  'compassion+nostalgia':     'Tender Memory',
  'admiration+nostalgia':     'Reverent Remembrance',
  'nostalgia+sympathy':       'Gentle Reminiscence',
  'empathy+nostalgia':        'Shared Memory',
  'nostalgia+romance':        'Sentimental Longing',

  // comfort +
  'comfort+gratitude':        'Grateful Ease',
  'comfort+love':             'Tender Warmth',
  'comfort+hope':             'Peaceful Optimism',
  'comfort+supported':        'Nurtured',
  'comfort+safe':             'Deep Security',
  'comfort+jealousy':         'Uneasy Comfort',
  'comfort+resentment':       'Hollow Comfort',
  'comfort+shame':            'Ashamed Ease',
  'comfort+guilt':            'Guilty Comfort',
  'comfort+rejection':        'Soothed Hurt',
  'betrayal+comfort':         'Cautious Warmth',
  'comfort+loneliness':       'Lonely Warmth',
  'comfort+disappointment':   'Consoled',
  'comfort+numbness':         'Numbed Comfort',
  'comfort+insecurity':       'Fragile Ease',
  'boredom+comfort':          'Restless Ease',
  'comfort+overwhelmed':      'Overwhelmed Calm',
  'comfort+triumph':          'Triumphant Relief',
  'comfort+craving':          'Soothing Desire',
  'comfort+excitement':       'Cosy Anticipation',
  'comfort+determination':    'Steady Resolve',
  'comfort+confidence':       'Assured Ease',
  'comfort+inspired':         'Relaxed Creativity',
  'comfort+compassion':       'Nurturing Warmth',
  'admiration+comfort':       'Admiring Ease',
  'comfort+sympathy':         'Gentle Warmth',
  'comfort+empathy':          'Nurturing Understanding',
  'comfort+romance':          'Intimate Warmth',

  // gratitude +
  'gratitude+love':           'Deep Appreciation',
  'gratitude+hope':           'Thankful Optimism',
  'gratitude+supported':      'Deeply Appreciated',
  'gratitude+safe':           'Thankful Security',
  'gratitude+jealousy':       'Grateful Longing',
  'gratitude+resentment':     'Conflicted Gratitude',
  'gratitude+shame':          'Humble Regret',
  'gratitude+guilt':          'Thankful Remorse',
  'gratitude+rejection':      'Gracious Resilience',
  'betrayal+gratitude':       'Grateful Despite Pain',
  'gratitude+loneliness':     'Thankful Solitude',
  'disappointment+gratitude': 'Tempered Appreciation',
  'gratitude+numbness':       'Hollow Appreciation',
  'gratitude+insecurity':     'Fragile Gratitude',
  'boredom+gratitude':        'Restless Appreciation',
  'gratitude+overwhelmed':    'Overwhelmed Thankfulness',
  'gratitude+triumph':        'Grateful Victory',
  'craving+gratitude':        'Yearning Appreciation',
  'excitement+gratitude':     'Enthusiastic Gratitude',
  'determination+gratitude':  'Driven Appreciation',
  'confidence+gratitude':     'Assured Thankfulness',
  'gratitude+inspired':       'Creatively Thankful',
  'compassion+gratitude':     'Generous Appreciation',
  'admiration+gratitude':     'Reverent Thankfulness',
  'gratitude+sympathy':       'Compassionate Thanks',
  'empathy+gratitude':        'Deeply Connected Thanks',
  'gratitude+romance':        'Tender Appreciation',

  // love +
  'hope+love':                'Devoted Optimism',
  'love+supported':           'Cherished',
  'love+safe':                'Secure Devotion',
  'jealousy+love':            'Possessive Love',
  'love+resentment':          'Complicated Love',
  'love+shame':               'Vulnerable Love',
  'guilt+love':               'Devoted Remorse',
  'love+rejection':           'Heartbroken Love',
  'betrayal+love':            'Shattered Love',
  'loneliness+love':          'Lonely Devotion',
  'disappointment+love':      'Disillusioned Love',
  'love+numbness':            'Faded Love',
  'insecurity+love':          'Anxious Attachment',
  'boredom+love':             'Stagnant Love',
  'love+overwhelmed':         'Overwhelming Devotion',
  'love+triumph':             'Victorious Love',
  'craving+love':             'Desperate Devotion',
  'excitement+love':          'Exhilarated Love',
  'determination+love':       'Resolute Devotion',
  'confidence+love':          'Assured Devotion',
  'inspired+love':            'Creative Devotion',
  'compassion+love':          'Unconditional Love',
  'admiration+love':          'Devoted Admiration',
  'love+sympathy':            'Tender Care',
  'empathy+love':             'Deep Connection',
  'love+romance':             'Passionate Devotion',

  // hope +
  'hope+supported':           'Encouraged',
  'hope+safe':                'Secure Hope',
  'hope+jealousy':            'Hopeful Longing',
  'hope+resentment':          'Bitter Hope',
  'hope+shame':               'Humble Hope',
  'guilt+hope':               'Hopeful Remorse',
  'hope+rejection':           'Resilient Hope',
  'betrayal+hope':            'Fragile Hope',
  'hope+loneliness':          'Hopeful Solitude',
  'disappointment+hope':      'Persistent Hope',
  'hope+numbness':            'Distant Hope',
  'hope+insecurity':          'Fragile Optimism',
  'boredom+hope':             'Restless Hope',
  'hope+overwhelmed':         'Overwhelmed Optimism',
  'hope+triumph':             'Fulfilled Hope',
  'craving+hope':             'Yearning Optimism',
  'excitement+hope':          'Eager Anticipation',
  'determination+hope':       'Resolute Optimism',
  'confidence+hope':          'Assured Optimism',
  'hope+inspired':            'Inspired Vision',
  'compassion+hope':          'Hopeful Caring',
  'admiration+hope':          'Inspired Hope',
  'hope+sympathy':            'Hopeful Kindness',
  'empathy+hope':             'Connected Hope',
  'hope+romance':             'Romantic Optimism',

  // supported +
  'safe+supported':           'Deeply Secure',
  'jealousy+supported':       'Guarded Connection',
  'resentment+supported':     'Reluctant Security',
  'shame+supported':          'Supported Vulnerability',
  'guilt+supported':          'Forgiven',
  'rejection+supported':      'Resilient Connection',
  'betrayal+supported':       'Cautious Trust',
  'loneliness+supported':     'Found Connection',
  'disappointment+supported': 'Consoled',
  'numbness+supported':       'Gently Held',
  'insecurity+supported':     'Reassured',
  'boredom+supported':        'Engaged',
  'overwhelmed+supported':    'Relieved',
  'supported+triumph':        'Celebrated',
  'craving+supported':        'Nurtured Desire',
  'excitement+supported':     'Encouraged Enthusiasm',
  'determination+supported':  'Empowered Drive',
  'confidence+supported':     'Backed Assurance',
  'inspired+supported':       'Encouraged Creativity',
  'compassion+supported':     'Cared For',
  'admiration+supported':     'Admired',
  'supported+sympathy':       'Understood',
  'empathy+supported':        'Deeply Seen',
  'romance+supported':        'Cherished Devotion',

  // safe +
  'jealousy+safe':            'Secure but Watchful',
  'resentment+safe':          'Safely Bitter',
  'safe+shame':               'Safely Vulnerable',
  'guilt+safe':               'Safely Remorseful',
  'rejection+safe':           'Safely Resilient',
  'betrayal+safe':            'Cautious Safety',
  'loneliness+safe':          'Safe Solitude',
  'disappointment+safe':      'Safely Disappointed',
  'numbness+safe':            'Safely Distant',
  'insecurity+safe':          'Tentative Security',
  'boredom+safe':             'Safely Restless',
  'overwhelmed+safe':         'Safely Overwhelmed',
  'safe+triumph':             'Secure Victory',
  'craving+safe':             'Safe Desire',
  'excitement+safe':          'Secure Anticipation',
  'determination+safe':       'Grounded Drive',
  'confidence+safe':          'Secure Confidence',
  'inspired+safe':            'Grounded Creativity',
  'compassion+safe':          'Safe Generosity',
  'admiration+safe':          'Secure Admiration',
  'safe+sympathy':            'Safe Kindness',
  'empathy+safe':             'Securely Connected',
  'romance+safe':             'Secure Intimacy',

  // jealousy +
  'jealousy+resentment':      'Toxic Envy',
  'jealousy+shame':           'Ashamed Jealousy',
  'guilt+jealousy':           'Guilty Possessiveness',
  'jealousy+rejection':       'Fearful Exclusion',
  'betrayal+jealousy':        'Betrayed Possessiveness',
  'jealousy+loneliness':      'Lonely Envy',
  'disappointment+jealousy':  'Bitter Disappointment',
  'jealousy+numbness':        'Hollow Envy',
  'insecurity+jealousy':      'Paranoid Insecurity',
  'boredom+jealousy':         'Restless Longing',
  'jealousy+overwhelmed':     'Consumed by Envy',
  'jealousy+triumph':         'Vindicated Envy',
  'craving+jealousy':         'Obsessive Longing',
  'excitement+jealousy':      'Frenzied Envy',
  'determination+jealousy':   'Driven by Envy',
  'confidence+jealousy':      'Competitive Edge',
  'inspired+jealousy':        'Ambitious Envy',
  'compassion+jealousy':      'Empathetic Longing',
  'admiration+jealousy':      'Envious Admiration',
  'jealousy+sympathy':        'Empathetic Envy',
  'empathy+jealousy':         'Understanding Envy',
  'jealousy+romance':         'Possessive Passion',

  // resentment +
  'resentment+shame':         'Shameful Bitterness',
  'guilt+resentment':         'Guilty Bitterness',
  'rejection+resentment':     'Bitter Exclusion',
  'betrayal+resentment':      'Deep Betrayal',
  'loneliness+resentment':    'Isolated Bitterness',
  'disappointment+resentment':'Bitter Disillusionment',
  'numbness+resentment':      'Hollow Bitterness',
  'insecurity+resentment':    'Defensive Bitterness',
  'boredom+resentment':       'Restless Bitterness',
  'overwhelmed+resentment':   'Overwhelmed Bitterness',
  'resentment+triumph':       'Vindicated Bitterness',
  'craving+resentment':       'Bitter Desire',
  'excitement+resentment':    'Conflicted Energy',
  'determination+resentment': 'Driven by Bitterness',
  'confidence+resentment':    'Assured Bitterness',
  'inspired+resentment':      'Bitter Creativity',
  'compassion+resentment':    'Troubled Compassion',
  'admiration+resentment':    'Reluctant Admiration',
  'resentment+sympathy':      'Bitter Empathy',
  'empathy+resentment':       'Understanding Bitterness',
  'resentment+romance':       'Complicated Passion',

  // shame +
  'guilt+shame':              'Deep Remorse',
  'rejection+shame':          'Humiliated',
  'betrayal+shame':           'Ashamed Betrayal',
  'loneliness+shame':         'Isolated Shame',
  'disappointment+shame':     'Deflated Shame',
  'numbness+shame':           'Hollow Shame',
  'insecurity+shame':         'Profound Self-doubt',
  'boredom+shame':            'Restless Shame',
  'overwhelmed+shame':        'Overwhelmed Shame',
  'shame+triumph':            'Hard-Won Self-worth',
  'craving+shame':            'Guilty Desire',
  'excitement+shame':         'Conflicted Enthusiasm',
  'determination+shame':      'Driven to Redeem',
  'confidence+shame':         'Fragile Confidence',
  'inspired+shame':           'Redemptive Creativity',
  'compassion+shame':         'Self-compassion',
  'admiration+shame':         'Ashamed Admiration',
  'shame+sympathy':           'Gentle Self-forgiveness',
  'empathy+shame':            'Understood Shame',
  'romance+shame':            'Vulnerable Intimacy',

  // guilt +
  'guilt+rejection':          'Guilty Exclusion',
  'betrayal+guilt':           'Guilty Betrayal',
  'guilt+loneliness':         'Lonely Remorse',
  'disappointment+guilt':     'Disappointed Remorse',
  'guilt+numbness':           'Hollow Remorse',
  'guilt+insecurity':         'Self-punishing Doubt',
  'boredom+guilt':            'Restless Remorse',
  'guilt+overwhelmed':        'Overwhelmed Remorse',
  'guilt+triumph':            'Guilty Victory',
  'craving+guilt':            'Conflicted Desire',
  'excitement+guilt':         'Guilty Excitement',
  'determination+guilt':      'Driven to Atone',
  'confidence+guilt':         'Assured Remorse',
  'guilt+inspired':           'Creative Redemption',
  'compassion+guilt':         'Empathetic Remorse',
  'admiration+guilt':         'Reverent Remorse',
  'guilt+sympathy':           'Gentle Remorse',
  'empathy+guilt':            'Connected Remorse',
  'guilt+romance':            'Devoted Remorse',

  // rejection +
  'betrayal+rejection':       'Abandoned',
  'loneliness+rejection':     'Deep Isolation',
  'disappointment+rejection': 'Crushed',
  'numbness+rejection':       'Hollow Exclusion',
  'insecurity+rejection':     'Fearful Exclusion',
  'boredom+rejection':        'Restless Exclusion',
  'overwhelmed+rejection':    'Overwhelmed Exclusion',
  'rejection+triumph':        'Resilient Victory',
  'craving+rejection':        'Desperate Longing',
  'excitement+rejection':     'Conflicted Anticipation',
  'determination+rejection':  'Resolute Resilience',
  'confidence+rejection':     'Assured Resilience',
  'inspired+rejection':       'Defiant Creativity',
  'compassion+rejection':     'Compassionate Resilience',
  'admiration+rejection':     'Humble Resilience',
  'rejection+sympathy':       'Gentle Exclusion',
  'empathy+rejection':        'Understood Exclusion',
  'rejection+romance':        'Unrequited Love',

  // betrayal +
  'betrayal+loneliness':      'Abandoned Solitude',
  'betrayal+disappointment':  'Shattered Trust',
  'betrayal+numbness':        'Numb Betrayal',
  'betrayal+insecurity':      'Shattered Security',
  'betrayal+boredom':         'Restless Betrayal',
  'betrayal+overwhelmed':     'Overwhelmed Betrayal',
  'betrayal+triumph':         'Survived Betrayal',
  'betrayal+craving':         'Desperate Need',
  'betrayal+excitement':      'Conflicted Trust',
  'betrayal+determination':   'Resolute Recovery',
  'betrayal+confidence':      'Rebuilding Trust',
  'betrayal+inspired':        'Rising from Betrayal',
  'betrayal+compassion':      'Forgiving Betrayal',
  'betrayal+admiration':      'Conflicted Loyalty',
  'betrayal+sympathy':        'Gentle Betrayal',
  'betrayal+empathy':         'Understanding Betrayal',
  'betrayal+romance':         'Broken Romance',

  // loneliness +
  'disappointment+loneliness':'Disillusioned Solitude',
  'loneliness+numbness':      'Empty Solitude',
  'insecurity+loneliness':    'Fearful Isolation',
  'boredom+loneliness':       'Restless Solitude',
  'loneliness+overwhelmed':   'Overwhelmed Isolation',
  'loneliness+triumph':       'Solitary Victory',
  'craving+loneliness':       'Yearning Solitude',
  'excitement+loneliness':    'Lonely Anticipation',
  'determination+loneliness': 'Resolute Solitude',
  'confidence+loneliness':    'Self-assured Solitude',
  'inspired+loneliness':      'Solitary Creativity',
  'compassion+loneliness':    'Reaching Out',
  'admiration+loneliness':    'Distant Admiration',
  'loneliness+sympathy':      'Gentle Solitude',
  'empathy+loneliness':       'Connected Isolation',
  'loneliness+romance':       'Lonely Longing',

  // disappointment +
  'disappointment+numbness':  'Hollow Disappointment',
  'disappointment+insecurity':'Deflated Confidence',
  'boredom+disappointment':   'Restless Disappointment',
  'disappointment+overwhelmed':'Crushed',
  'disappointment+triumph':   'Hard-Won Comeback',
  'craving+disappointment':   'Unfulfilled Desire',
  'disappointment+excitement':'Conflicted Anticipation',
  'determination+disappointment':'Resolute Recovery',
  'confidence+disappointment':'Shaken Confidence',
  'disappointment+inspired':  'Rising from Failure',
  'compassion+disappointment':'Gentle Disappointment',
  'admiration+disappointment':'Humbled Admiration',
  'disappointment+sympathy':  'Gentle Let-down',
  'empathy+disappointment':   'Shared Disappointment',
  'disappointment+romance':   'Disillusioned Love',

  // numbness +
  'insecurity+numbness':      'Empty Self-doubt',
  'boredom+numbness':         'Total Apathy',
  'numbness+overwhelmed':     'Shut Down',
  'numbness+triumph':         'Hollow Victory',
  'craving+numbness':         'Empty Desire',
  'excitement+numbness':      'Muted Enthusiasm',
  'determination+numbness':   'Going Through Motions',
  'confidence+numbness':      'Empty Confidence',
  'inspired+numbness':        'Faded Inspiration',
  'compassion+numbness':      'Distant Care',
  'admiration+numbness':      'Hollow Admiration',
  'numbness+sympathy':        'Distant Kindness',
  'empathy+numbness':         'Disconnected Understanding',
  'numbness+romance':         'Faded Passion',

  // insecurity +
  'boredom+insecurity':       'Restless Self-doubt',
  'insecurity+overwhelmed':   'Paralysing Self-doubt',
  'insecurity+triumph':       'Surprised by Success',
  'craving+insecurity':       'Desperate Need',
  'excitement+insecurity':    'Nervous Excitement',
  'determination+insecurity': 'Driven Despite Doubt',
  'confidence+insecurity':    'Imposter Syndrome',
  'inspired+insecurity':      'Doubting Creativity',
  'compassion+insecurity':    'Gentle Self-care',
  'admiration+insecurity':    'Intimidated Admiration',
  'insecurity+sympathy':      'Gentle Self-doubt',
  'empathy+insecurity':       'Understanding Self-doubt',
  'insecurity+romance':       'Anxious Love',

  // boredom +
  'boredom+overwhelmed':      'Exhausted Restlessness',
  'boredom+triumph':          'Uninspired Victory',
  'boredom+craving':          'Restless Desire',
  'boredom+excitement':       'Seeking Stimulation',
  'boredom+determination':    'Forced Drive',
  'boredom+confidence':       'Assured Restlessness',
  'boredom+inspired':         'Seeking Inspiration',
  'boredom+compassion':       'Gentle Restlessness',
  'admiration+boredom':       'Uninspired Admiration',
  'boredom+sympathy':         'Restless Kindness',
  'boredom+empathy':          'Restless Understanding',
  'boredom+romance':          'Stagnant Passion',

  // overwhelmed +
  'overwhelmed+triumph':      'Exhausted Victory',
  'craving+overwhelmed':      'Desperate Overwhelm',
  'excitement+overwhelmed':   'Frenzied Anticipation',
  'determination+overwhelmed':'Burning Out',
  'confidence+overwhelmed':   'Overwhelmed Assurance',
  'inspired+overwhelmed':     'Creative Overload',
  'compassion+overwhelmed':   'Overwhelmed Caring',
  'admiration+overwhelmed':   'Overwhelmed Admiration',
  'overwhelmed+sympathy':     'Overwhelmed Kindness',
  'empathy+overwhelmed':      'Overwhelmed Understanding',
  'overwhelmed+romance':      'Overwhelming Passion',

  // triumph +
  'craving+triumph':          'Victorious Desire',
  'excitement+triumph':       'Exhilarated Victory',
  'determination+triumph':    'Hard-Won Victory',
  'confidence+triumph':       'Assured Victory',
  'inspired+triumph':         'Creative Victory',
  'compassion+triumph':       'Generous Victory',
  'admiration+triumph':       'Admired Achievement',
  'sympathy+triumph':         'Celebrated Victory',
  'empathy+triumph':          'Shared Victory',
  'romance+triumph':          'Triumphant Love',

  // craving +
  'craving+excitement':       'Intense Anticipation',
  'craving+determination':    'Relentless Drive',
  'confidence+craving':       'Assured Desire',
  'craving+inspired':         'Hungry Creativity',
  'compassion+craving':       'Yearning Compassion',
  'admiration+craving':       'Longing Admiration',
  'craving+sympathy':         'Yearning Kindness',
  'craving+empathy':          'Deeply Felt Desire',
  'craving+romance':          'Intense Longing',

  // excitement +
  'determination+excitement': 'Driven Enthusiasm',
  'confidence+excitement':    'Bold Enthusiasm',
  'excitement+inspired':      'Creative Energy',
  'compassion+excitement':    'Enthusiastic Caring',
  'admiration+excitement':    'Inspired Excitement',
  'excitement+sympathy':      'Enthusiastic Kindness',
  'empathy+excitement':       'Enthusiastic Connection',
  'excitement+romance':       'Passionate Anticipation',

  // determination +
  'confidence+determination': 'Unstoppable Drive',
  'determination+inspired':   'Visionary Drive',
  'compassion+determination': 'Driven Caring',
  'admiration+determination': 'Inspired Drive',
  'determination+sympathy':   'Driven Kindness',
  'empathy+determination':    'Driven Understanding',
  'determination+romance':    'Devoted Drive',

  // confidence +
  'confidence+inspired':      'Visionary Confidence',
  'compassion+confidence':    'Assured Caring',
  'admiration+confidence':    'Inspired Confidence',
  'confidence+sympathy':      'Assured Kindness',
  'confidence+empathy':       'Assured Understanding',
  'confidence+romance':       'Bold Passion',

  // inspired +
  'compassion+inspired':      'Creative Compassion',
  'admiration+inspired':      'Inspired Admiration',
  'inspired+sympathy':        'Creative Kindness',
  'empathy+inspired':         'Inspired Connection',
  'inspired+romance':         'Creative Passion',

  // compassion +
  'admiration+compassion':    'Reverent Care',
  'compassion+sympathy':      'Deep Empathy',
  'compassion+empathy':       'Profound Compassion',
  'compassion+romance':       'Tender Love',

  // admiration +
  'admiration+sympathy':      'Reverent Kindness',
  'admiration+empathy':       'Deep Admiration',
  'admiration+romance':       'Devoted Admiration',

  // sympathy +
  'empathy+sympathy':         'Profound Understanding',
  'romance+sympathy':         'Tender Understanding',

  // empathy +
  'empathy+romance':          'Deeply Connected Love',
};

// ─────────────────────────────────────────────────────────────────────────────
// HELPER  — order-independent blend lookup
// Usage:  getBlend('happiness', 'anger')  →  'Passionate Fury'
// ─────────────────────────────────────────────────────────────────────────────

function getBlend(a, b) {
  const key = [a.toLowerCase(), b.toLowerCase()].sort().join('+');
  return BLEND_MAP_FULL[key] || 'Complex Mix';
}